[versions]
kotlin = "2.3.0"
ktor = "3.4.0"
logback = "1.5.27"
logstash-encoder = "9.0"
bigquery = "2.58.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
jwt = "4.5.0"
bouncy-castle = "1.83"
kafka = "4.1.1"
expedia-graphql = "8.8.1"
junit = "6.0.2"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

expedia-graphql-ktor-client = { module = "com.expediagroup:graphql-kotlin-ktor-client", version.ref = "expedia-graphql" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }

auth0-java-jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }
bouncy-castle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncy-castle" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-encoder" }

google-cloud-bigquery = { module = "com.google.cloud:google-cloud-bigquery", version.ref = "bigquery" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
expedia-graphql = { id = "com.expediagroup.graphql", version.ref = "expedia-graphql" }

[bundles]
ktor-client = [
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json"
]

logging = [
    "logback-classic",
    "logstash-logback-encoder"
]

github-auth = [
    "auth0-java-jwt",
    "bouncy-castle-bcpkix"
]

testing = [
    "junit-jupiter",
    "ktor-client-mock",
    "junit-platform-launcher"
]